context:
  org: peco
  name: peco
  version: "0.5.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ org }}/${{ name|lower }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 8e32c8af533e03795f27feb4ee134960611d2fc0266528b1c512a6f1f065b164

build:
  number: 0

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses
    - make

tests:
  - script:
    - ${{ name }} --version

about:
  homepage: https://github.com/${{ org }}/${{ name }}
  repository: https://github.com/${{ org }}/${{ name }}
  documentation: https://github.com/${{ org }}/${{ name }}/blob/v${{ version }}/README.md
  summary: "Simplistic interactive filtering tool"
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  description: |
    `peco` can be a great tool to filter stuff like logs,
    process stats, find files, because unlike grep,
    you can type as you think and look through the current results.

extra:
  recipe-maintainers:
    - eunos-1128
